### ISSUE TITLE
mssql-conf.py does not ensure subprocess.call receives strings-only dict

### ISSUE THREAD

**Issue by mloskot** [Microsoft/mssql-docker#111]
UPDATE: I've realised Microsoft Connect might better place to submit this issue, so I added it there too:
https://connect.microsoft.com/SQLServer/feedback/details/3136158

I run `mssql-conf -n setup` on Ubuntu, but I think this bug also applies to docker images with SQL Server 2017 on Linux:

```
$ export ACCEPT_EULA=Y
$ export MSSQL_SA_PASSWORD="Password12!"
$ sudo -E bash -c '/opt/mssql/bin/mssql-conf -n setup'           # REQUIRED to preserve the env
...
Traceback (most recent call last):
  File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 260, in <module>
    main()
  File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 256, in main
    processCommands()
  File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 184, in processCommands
    COMMAND_TABLE[args.which]()
  File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 57, in handleSetup
    exit(mssqlconfhelper.setupSqlServer(noprompt=args.noprompt))
  File "/opt/mssql/lib/mssql-conf/mssqlconfhelper.py", line 618, in setupSqlServer
    ret = configureSqlservrWithArguments("--setup --reset-sa-password", MSSQL_SA_PASSWORD=encodedPassword)
  File "/opt/mssql/lib/mssql-conf/mssqlconfhelper.py", line 539, in configureSqlservrWithArguments
    return subprocess.call(args, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
TypeError: execve() arg 3 contains a non-string value
```

This simple patch applied to `/opt/mssql/lib/mssql-conf/mssqlconfhelper.py` ensures env dictionary contains string-only entries as required by `subprocess.call`:

```
--- /opt/mssql/lib/mssql-conf/mssqlconfhelper.py	2017-06-17 19:10:03.511047973 +0200
+++ /opt/mssql/lib/mssql-conf/mssqlconfhelper.fixed.py	2017-06-17 19:09:52.829709973 +0200
@@ -533,6 +533,7 @@
     args = [invokeSqlservrScript] + list(args)
     env = dict(os.environ)
     env.update(kwargs)
+    env = {str(k): str(v) for k, v in env.items()}    
     print("Configuring SQL Server...")
     return subprocess.call(args, env=env)
 
```

**Comment by twright-msft** [comment]
Thanks for reporting this. We are working on a fix.

**Comment by twright-msft** [comment]
This will be fixed in the next release of SQL Server.  Thanks again for the heads up!

**Comment by mloskot** [comment]
Good news, thanks!

**Comment by mloskot** [comment]
I confirm the bug has been fixed.
Tested with Microsoft SQL Server 2017 (RC2) 14.0.900.75
