### ISSUE TITLE
CentOS image has stopped working as of approximately today

### ISSUE THREAD

**Issue by zzzeek** [Microsoft/mssql-docker#248]
I run my own version of the Centos Docker container, however the one that is published here is failing for the same reasons:

Error: The evaluation period has expired.
This program has encountered a fatal error and cannot continue running.
The following diagnostic information is available:
       Reason: 0x00000001
       Signal: SIGSEGV - Segmentation fault (11)
   Stacktrace: 0000557975e2add7 00007fadce0b85e0 0000557975e3a052 
               0000557975e237cb 0000557975e22f49 
      Process: 1 - sqlservr
       Thread: 31 (application thread 0x1060)
  Instance Id: a0ed4be6-3b45-4205-b226-fe740dccc4e3
     Crash Id: 
  Build stamp: ff4c991962e5ff435939d15a8b81bdfaa2f354495851a34781907e95e2b94e88

Steps to reproduce:

# git clone https://github.com/Microsoft/mssql-docker.git
# cd mssql-docker/linux/preview/CentOS
# make
# make run

the container will be stopped, docker logs shows the above error.

full run below:

[root@dell CentOS]# make
docker build --pull -t microsoft/mssql-server-linux:centos7-v14.0 -t microsoft/mssql-server-linux .
Sending build context to Docker daemon 5.632 kB
Step 1/7 : FROM centos:7
Trying to pull repository docker.io/library/centos ... 
sha256:2671f7a3eea36ce43609e9fe7435ade83094291055f1c96d9d1d1d7c0b986a5d: Pulling from docker.io/library/centos
Digest: sha256:2671f7a3eea36ce43609e9fe7435ade83094291055f1c96d9d1d1d7c0b986a5d
Status: Image is up to date for docker.io/centos:7
 ---> ff426288ea90
Step 2/7 : LABEL name "microsoft/mssql-server-linux" vendor "Microsoft" version "14.0" release "1" summary "MS SQL Server Developer Edition" description "MS SQL Server is ....." url "https://www.microsoft.com/en-us/sql-server/" run 'docker run --name ${NAME}         -e ACCEPT_EULA=Y -e SA_PASSWORD=yourStrong@Password         -p 1433:1433         -d  ${IMAGE}' io.k8s.description "MS SQL Server is ....." io.k8s.display-name "MS SQL Server Developer Edition"
 ---> Running in e6c77a61c4ff
 ---> e4c4e53a3bda
Removing intermediate container e6c77a61c4ff
Step 3/7 : RUN curl https://packages.microsoft.com/config/rhel/7/mssql-server.repo > /etc/yum.repos.d/mssql-server.repo &&     curl https://packages.microsoft.com/config/rhel/7/prod.repo > /etc/yum.repos.d/msprod.repo &&     ACCEPT_EULA=Y yum install -y mssql-server mssql-tools &&     yum clean all
 ---> Running in 5165f5bc8f92
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   220  100   220    0     0    716      0 --:--:-- --:--:-- --:--:--   718
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   193  100   193    0     0    974      0 --:--:-- --:--:-- --:--:--   979
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
 * base: mirrors.centos.webair.com
 * extras: mirror.oss.ou.edu
 * updates: mirror.math.princeton.edu
Resolving Dependencies
--> Running transaction check
---> Package mssql-server.x86_64 0:14.0.900.75-1 will be installed
--> Processing Dependency: openssl < 1:1.1.0 for package: mssql-server-14.0.900.75-1.x86_64
--> Processing Dependency: openssl >= 1:1.0.1 for package: mssql-server-14.0.900.75-1.x86_64
--> Processing Dependency: bzip2 for package: mssql-server-14.0.900.75-1.x86_64
--> Processing Dependency: numactl-libs for package: mssql-server-14.0.900.75-1.x86_64
--> Processing Dependency: gdb for package: mssql-server-14.0.900.75-1.x86_64
--> Processing Dependency: libsss_nss_idmap for package: mssql-server-14.0.900.75-1.x86_64
---> Package mssql-tools.x86_64 0:14.0.6.0-1 will be installed
--> Processing Dependency: msodbcsql < 13.2.0.0 for package: mssql-tools-14.0.6.0-1.x86_64
--> Processing Dependency: msodbcsql >= 13.1.0.0 for package: mssql-tools-14.0.6.0-1.x86_64
--> Running transaction check
---> Package bzip2.x86_64 0:1.0.6-13.el7 will be installed
---> Package gdb.x86_64 0:7.6.1-100.el7_4.1 will be installed
---> Package libsss_nss_idmap.x86_64 0:1.15.2-50.el7_4.8 will be installed
---> Package msodbcsql.x86_64 0:13.1.9.2-1 will be installed
--> Processing Dependency: unixODBC >= 2.3.1 for package: msodbcsql-13.1.9.2-1.x86_64
--> Processing Dependency: e2fsprogs for package: msodbcsql-13.1.9.2-1.x86_64
--> Processing Dependency: libodbcinst.so.2()(64bit) for package: msodbcsql-13.1.9.2-1.x86_64
---> Package numactl-libs.x86_64 0:2.0.9-6.el7_2 will be installed
---> Package openssl.x86_64 1:1.0.2k-8.el7 will be installed
--> Processing Dependency: make for package: 1:openssl-1.0.2k-8.el7.x86_64
--> Running transaction check
---> Package e2fsprogs.x86_64 0:1.42.9-10.el7 will be installed
--> Processing Dependency: libss = 1.42.9-10.el7 for package: e2fsprogs-1.42.9-10.el7.x86_64
--> Processing Dependency: e2fsprogs-libs(x86-64) = 1.42.9-10.el7 for package: e2fsprogs-1.42.9-10.el7.x86_64
--> Processing Dependency: libss.so.2()(64bit) for package: e2fsprogs-1.42.9-10.el7.x86_64
--> Processing Dependency: libext2fs.so.2()(64bit) for package: e2fsprogs-1.42.9-10.el7.x86_64
--> Processing Dependency: libe2p.so.2()(64bit) for package: e2fsprogs-1.42.9-10.el7.x86_64
---> Package make.x86_64 1:3.82-23.el7 will be installed
---> Package unixODBC.x86_64 0:2.3.1-11.el7 will be installed
--> Processing Dependency: libltdl.so.7()(64bit) for package: unixODBC-2.3.1-11.el7.x86_64
--> Running transaction check
---> Package e2fsprogs-libs.x86_64 0:1.42.9-10.el7 will be installed
---> Package libss.x86_64 0:1.42.9-10.el7 will be installed
---> Package libtool-ltdl.x86_64 0:2.4.2-22.el7_3 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package          Arch   Version           Repository                      Size
================================================================================
Installing:
 mssql-server     x86_64 14.0.900.75-1     packages-microsoft-com-mssql-server
                                                                          165 M
 mssql-tools      x86_64 14.0.6.0-1        packages-microsoft-com-prod    249 k
Installing for dependencies:
 bzip2            x86_64 1.0.6-13.el7      base                            52 k
 e2fsprogs        x86_64 1.42.9-10.el7     base                           698 k
 e2fsprogs-libs   x86_64 1.42.9-10.el7     base                           166 k
 gdb              x86_64 7.6.1-100.el7_4.1 updates                        2.4 M
 libss            x86_64 1.42.9-10.el7     base                            45 k
 libsss_nss_idmap x86_64 1.15.2-50.el7_4.8 updates                        131 k
 libtool-ltdl     x86_64 2.4.2-22.el7_3    base                            49 k
 make             x86_64 1:3.82-23.el7     base                           420 k
 msodbcsql        x86_64 13.1.9.2-1        packages-microsoft-com-prod    4.0 M
 numactl-libs     x86_64 2.0.9-6.el7_2     base                            29 k
 openssl          x86_64 1:1.0.2k-8.el7    base                           492 k
 unixODBC         x86_64 2.3.1-11.el7      base                           413 k

Transaction Summary
================================================================================
Install  2 Packages (+12 Dependent packages)

Total download size: 174 M
Installed size: 183 M
Downloading packages:
warning: /var/cache/yum/x86_64/7/base/packages/bzip2-1.0.6-13.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
Public key for bzip2-1.0.6-13.el7.x86_64.rpm is not installed
Public key for gdb-7.6.1-100.el7_4.1.x86_64.rpm is not installed
warning: /var/cache/yum/x86_64/7/packages-microsoft-com-prod/packages/msodbcsql-13.1.9.2-1.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
Public key for msodbcsql-13.1.9.2-1.x86_64.rpm is not installed
Public key for mssql-server-14.0.900.75-1.x86_64.rpm is not installed
--------------------------------------------------------------------------------
Total                                              7.7 MB/s | 174 MB  00:22     
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Importing GPG key 0xF4A80EB5:
 Userid     : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
 Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
 Package    : centos-release-7-4.1708.el7.centos.x86_64 (@CentOS)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Retrieving key from https://packages.microsoft.com/keys/microsoft.asc
Importing GPG key 0xBE1229CF:
 Userid     : "Microsoft (Release signing) <gpgsecurity@microsoft.com>"
 Fingerprint: bc52 8686 b50d 79e3 39d3 721c eb3e 94ad be12 29cf
 From       : https://packages.microsoft.com/keys/microsoft.asc
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : libsss_nss_idmap-1.15.2-50.el7_4.8.x86_64                   1/14 
  Installing : numactl-libs-2.0.9-6.el7_2.x86_64                           2/14 
  Installing : 1:make-3.82-23.el7.x86_64                                   3/14 
  Installing : 1:openssl-1.0.2k-8.el7.x86_64                               4/14 
  Installing : libtool-ltdl-2.4.2-22.el7_3.x86_64                          5/14 
  Installing : unixODBC-2.3.1-11.el7.x86_64                                6/14 
  Installing : e2fsprogs-libs-1.42.9-10.el7.x86_64                         7/14 
  Installing : gdb-7.6.1-100.el7_4.1.x86_64                                8/14 
  Installing : bzip2-1.0.6-13.el7.x86_64                                   9/14 
  Installing : libss-1.42.9-10.el7.x86_64                                 10/14 
  Installing : e2fsprogs-1.42.9-10.el7.x86_64                             11/14 
  Installing : msodbcsql-13.1.9.2-1.x86_64                                12/14 
  Installing : mssql-tools-14.0.6.0-1.x86_64                              13/14 
  Installing : mssql-server-14.0.900.75-1.x86_64                          14/14 

+--------------------------------------------------------------+
Please run 'sudo /opt/mssql/bin/mssql-conf setup'
to complete the setup of Microsoft SQL Server
+--------------------------------------------------------------+

  Verifying  : libss-1.42.9-10.el7.x86_64                                  1/14 
  Verifying  : mssql-server-14.0.900.75-1.x86_64                           2/14 
  Verifying  : 1:openssl-1.0.2k-8.el7.x86_64                               3/14 
  Verifying  : bzip2-1.0.6-13.el7.x86_64                                   4/14 
  Verifying  : unixODBC-2.3.1-11.el7.x86_64                                5/14 
  Verifying  : mssql-tools-14.0.6.0-1.x86_64                               6/14 
  Verifying  : e2fsprogs-1.42.9-10.el7.x86_64                              7/14 
  Verifying  : gdb-7.6.1-100.el7_4.1.x86_64                                8/14 
  Verifying  : e2fsprogs-libs-1.42.9-10.el7.x86_64                         9/14 
  Verifying  : libtool-ltdl-2.4.2-22.el7_3.x86_64                         10/14 
  Verifying  : 1:make-3.82-23.el7.x86_64                                  11/14 
  Verifying  : numactl-libs-2.0.9-6.el7_2.x86_64                          12/14 
  Verifying  : msodbcsql-13.1.9.2-1.x86_64                                13/14 
  Verifying  : libsss_nss_idmap-1.15.2-50.el7_4.8.x86_64                  14/14 

Installed:
  mssql-server.x86_64 0:14.0.900.75-1      mssql-tools.x86_64 0:14.0.6.0-1     

Dependency Installed:
  bzip2.x86_64 0:1.0.6-13.el7                                                   
  e2fsprogs.x86_64 0:1.42.9-10.el7                                              
  e2fsprogs-libs.x86_64 0:1.42.9-10.el7                                         
  gdb.x86_64 0:7.6.1-100.el7_4.1                                                
  libss.x86_64 0:1.42.9-10.el7                                                  
  libsss_nss_idmap.x86_64 0:1.15.2-50.el7_4.8                                   
  libtool-ltdl.x86_64 0:2.4.2-22.el7_3                                          
  make.x86_64 1:3.82-23.el7                                                     
  msodbcsql.x86_64 0:13.1.9.2-1                                                 
  numactl-libs.x86_64 0:2.0.9-6.el7_2                                           
  openssl.x86_64 1:1.0.2k-8.el7                                                 
  unixODBC.x86_64 0:2.3.1-11.el7                                                

Complete!
Loaded plugins: fastestmirror, ovl
Cleaning repos: base extras packages-microsoft-com-mssql-server
              : packages-microsoft-com-prod updates
Cleaning up everything
Maybe you want: rm -rf /var/cache/yum, to also free up space taken by orphaned data from disabled or removed repos
Cleaning up list of fastest mirrors
 ---> 94d50e01add1
Removing intermediate container 5165f5bc8f92
Step 4/7 : ENV PATH ${PATH}:/opt/mssql/bin:/opt/mssql-tools/bin
 ---> Running in af0736a22048
 ---> cdc807ed6722
Removing intermediate container af0736a22048
Step 5/7 : EXPOSE 1433
 ---> Running in 296843e750dc
 ---> 303fa7bb07e5
Removing intermediate container 296843e750dc
Step 6/7 : VOLUME /var/opt/mssql
 ---> Running in 273fd780dfa6
 ---> f5db5949ed26
Removing intermediate container 273fd780dfa6
Step 7/7 : CMD sqlservr
 ---> Running in 8ca59214fb64
 ---> eaa176cc36c5
Removing intermediate container 8ca59214fb64
Successfully built eaa176cc36c5
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
microsoft/mssql-server-linux   centos7-v14.0       eaa176cc36c5        1 second ago        1.17 GB

[root@dell CentOS]# docker images
REPOSITORY                               TAG                 IMAGE ID            CREATED              SIZE
microsoft/mssql-server-linux             centos7-v14.0       eaa176cc36c5        About a minute ago   1.17 GB
microsoft/mssql-server-linux             latest              eaa176cc36c5        About a minute ago   1.17 GB
docker.io/microsoft/mssql-server-linux   2017-latest         cb3198f4b4d3        2 weeks ago          1.35 GB
docker.io/centos                         7                   ff426288ea90        2 weeks ago          207 MB
docker.io/centos                         latest              196e0ce0c9fb        4 months ago         197 MB
docker.io/centos                         <none>              328edcd84f1b        5 months ago         193 MB

[root@dell CentOS]# make run
docker run -e ACCEPT_EULA=Y -e SA_PASSWORD=yourStrong@Password -p 1433:1433 -d microsoft/mssql-server-linux:centos7-v14.0
1dbd5ae52d533e502592eebe4d75ee0a0f554350f6fa1c464af8497ebba0213a

[root@dell CentOS]# docker ps 
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                        NAMES

[root@dell CentOS]# docker ps  --all
CONTAINER ID        IMAGE                                        COMMAND                  CREATED             STATUS                        PORTS                                                        NAMES
1dbd5ae52d53        microsoft/mssql-server-linux:centos7-v14.0   "/bin/sh -c sqlservr"    21 seconds ago      Exited (139) 19 seconds ago                                                                dazzling_bhabha

[root@dell CentOS]# docker logs dazzling_bhabha 
Error: The evaluation period has expired.
This program has encountered a fatal error and cannot continue running.
The following diagnostic information is available:
       Reason: 0x00000001
       Signal: SIGSEGV - Segmentation fault (11)
   Stacktrace: 0000557975e2add7 00007fadce0b85e0 0000557975e3a052 
               0000557975e237cb 0000557975e22f49 
      Process: 1 - sqlservr
       Thread: 31 (application thread 0x1060)
  Instance Id: a0ed4be6-3b45-4205-b226-fe740dccc4e3
     Crash Id: 
  Build stamp: ff4c991962e5ff435939d15a8b81bdfaa2f354495851a34781907e95e2b94e88

**Comment by sirio3mil** [comment]
I try to make my own [dockerfile](https://github.com/sirio3mil/docker-sqlsrv-full/blob/centos/Dockerfile) using centos but fail:

```
Step 4/5 : RUN /opt/mssql/bin/mssql-conf -n setup ---> Running in 742af9f7de7b 
[91mTraceback (most recent call last): 
File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 277, in <module> main() 
File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 273, in main processCommands() 
File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 197, in processCommands COMMAND_TABLE[args.which]() 
File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 54, in handleSetup exit(mssqlconfhelper.setupSqlServer(eulaAccepted, noprompt=args.noprompt)) 
File "/opt/mssql/lib/mssql-conf/mssqlconfhelper.py", line 795, in setupSqlServer if not checkInstall(): 
File "/opt/mssql/lib/mssql-conf/mssqlconfhelper.py", line 765, in checkInstall return runScript(checkInstallScript, True) == 0 
File "/opt/mssql/lib/mssql-conf/mssqlconfhelper.py", line 754, in runScript return subprocess.call([sudo, "-EH", pathToScript]) 
File "/usr/lib64/python2.7/subprocess.py", line 524, in call return Popen(*popenargs, **kwargs).wait() 
File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__ errread, errwrite) 
File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child raise child_exception OSError: [Errno 2] No such file or directory
[0m Removing intermediate container 742af9f7de7b 
The command '/bin/sh -c /opt/mssql/bin/mssql-conf -n setup' returned a non-zero code: 1
```
