### ISSUE TITLE
need a way to initialise the data directory manually

### ISSUE THREAD

**Issue by jasonblewis** [Microsoft/mssql-docker#269]
It would be great if there was a way to initialise the data directory and return control to the entrypoint, thus avoiding situations like #229 and #120 

Both postgresql and mysql make use of this in their dockerfiles.

The problem with calling sqlservr and running in the background from the entrypoint script (as per #229) is that it won't have a PID of 1, which means docker start/stop won't be acting on the process directly. i think this could lead to data loss or corruption

In mysql you can call `mysql --initialize` to create the database 
[https://github.com/Microsoft/mssql-docker.git](url)
[https://dev.mysql.com/doc/refman/5.7/en/data-directory-initialization-mysqld.html](url)

in postgresql they have `initdb`
[https://dev.mysql.com/doc/refman/5.7/en/data-directory-initialization-mysqld.html](url)
[https://www.postgresql.org/docs/9.5/static/app-initdb.html](url)

also see:
[https://success.docker.com/article/Use_a_script_to_initialize_stateful_container_data](url)

**Comment by IvanFarkas** [comment]
Exactly.
This should be **clearly** stated in the online documents how to **safely** and **reliably initialize the database** in the **docker-entrypoint.sh** or by any other means, fully taken advantage of the Docker infrastructure.
If this feature, capability or integration step is not available yet that also should be stated.
Any suggestions?

**Comment by jasonblewis** [comment]
I've discvered there is the mssql-conf command, which seems to have an "install" option. See https://docs.microsoft.com/en-us/sql/linux/sample-unattended-install-ubuntu however this doesn't work in the docker enviromnent.

```
root@2e2a20c4219a:/opt/mssql/bin# ./mssql-conf setup
Traceback (most recent call last):
  File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 277, in <module>
    main()
  File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 273, in main
    processCommands()
  File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 197, in processCommands
    COMMAND_TABLE[args.which]()
  File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 54, in handleSetup
    exit(mssqlconfhelper.setupSqlServer(eulaAccepted, noprompt=args.noprompt))
  File "/opt/mssql/lib/mssql-conf/mssqlconfhelper.py", line 795, in setupSqlServer
    if not checkInstall():
  File "/opt/mssql/lib/mssql-conf/mssqlconfhelper.py", line 765, in checkInstall
    return runScript(checkInstallScript, True) == 0
  File "/opt/mssql/lib/mssql-conf/mssqlconfhelper.py", line 754, in runScript
    return subprocess.call([sudo, "-EH", pathToScript])
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

There is also `sqlservr --force-install` but that seems undocumented, and doesn't exit sqlservr after it finishes

**Comment by jasonblewis** [comment]
sqlservr has an undocumented option --setup  which seems to be what we want. I haven't worked out how to successfully run it from an entrypoint script yet though

**Comment by twright-msft** [comment]
All of the configuration setting changes that `mssql-conf setup` does can also be set at `docker run` time via env variables.  

https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables

Is this what you are looking for?
MSSQL_DATA_DIR
MSSQL_LOG_DIR
MSSQL_BACKUP_DIR
MSSQL_DUMP_DIR

**Comment by samuel-gay** [comment]
Not sure if this is useful, since you posted so long ago. I had a very similar error. It took a lot of digging, but I eventually realized that the docker image I was using didn't have sudo installed (centos/systemd:latest). The error event mentions it in the error... *forehead slap*
File "/opt/mssql/lib/mssql-conf/mssqlconfhelper.py", line 754, in runScript
    return subprocess.call([**sudo**, "-EH", pathToScript])

**Comment by swasheck** [comment]
@twright-msft These configuration settings are for the linux image and seemingly do not work with the windows-developer image. Is there a way to expose this to the windows container image as well? I'd like to be able to persist master settings (logins and such) but that doesn't really seem like a possibility at this point.

**Comment by twright-msft** [comment]
No, sorry they are not yet available on the Windows container image.  As part of the work we are doing to create more official Windows container images we are going to make them align to the Linux images on things like this - env vars, mssql.conf file, etc. so there is consistency between Windows and Linux container semantics.
