### ISSUE TITLE
Create database on volume in (mssql-server-windows) container fails

### ISSUE THREAD

**Issue by CPRowan** [Microsoft/mssql-docker#344]
After starting a container with this command:  

docker run -d -p 51435:1433  -v C:\Users\CR037589\DockerData:U: --name sqldvlp03 --hostname sqldvlp03 -e sa_password=Passw[0]rd -e ACCEPT_EULA=Y microsoft/mssql-server-windows-developer

an attempt to create a database with the files on the U: drive in the container fails with the message below: 

Msg 5177, Level 16, State 1, Line 1
An unexpected error occurred while checking the sector size for file 'U:\Data-01\Data_Dev\SMSTHtndSFDB.mdf'. Move the file to a local NTFS volume, where the sector size can be retrieved. Check the SQL Server error log for more information.
Msg 1802, Level 16, State 4, Line 1
CREATE DATABASE failed. Some file names listed could not be created. Check related errors.

I was able to access the U: drive in the container through a powershell session and create folders on the drive, but SQL Server can't seem to create the database files on the drive. I connect to the container using SA in order to create the database. 

Seems like this should be supported, or am I doing something wrong?

**Comment by jonathanantoine** [comment]
Same issue for me, this occurs randomly while peforming my integration tests which create new database.

**Comment by rafaelcaviquioli** [comment]
Same issue for me,

**Comment by CPRowan** [comment]
Any update on this issue?

**Comment by CPRowan** [comment]
Any update on this issue? 

I tried the workaround documented at https://blog.sixeyed.com/docker-volumes-on-windows-the-case-of-the-g-drive/ but got the same error.

**Comment by oneacik** [comment]
I changed container to express one.
It seems to have stopped flaking.
Maybe not solution but a clue.

**Comment by abjrcode** [comment]
We have the same problem as well. To give you some context:
We have a build server running the build in a container, the root container in turn compiles a .NET Core solution and runs xUnit tests.
Some of the tests spin up a SQL Server container.
Randomly this fails with a similar stack trace:

> System.Data.SqlClient.SqlException : An unexpected error occurred while checking the sector size for file '/var/opt/mssql/data/sample-b4cff475-28eb-43a3-8e10-96409ea3e76a.mdf'. Move the file to a local NTFS volume, where the sector size can be retrieved. Check the SQL Server error log for more information.
CREATE DATABASE failed. Some file names listed could not be created. Check related errors.
User does not have permission to alter database 'sample-b4cff475-28eb-43a3-8e10-96409ea3e76a', the database does not exist, or the database is not in a state that allows access checks.
ALTER DATABASE statement failed.
User does not have permission to alter database 'sample-b4cff475-28eb-43a3-8e10-96409ea3e76a', the database does not exist, or the database is not in a state that allows access checks.
ALTER DATABASE statement failed.
User does not have permission to alter database 'sample-b4cff475-28eb-43a3-8e10-96409ea3e76a', the database does not exist, or the database is not in a state that allows access checks.
ALTER DATABASE statement failed.
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action1 wrapCloseInAction) at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action1 wrapCloseInAction)
at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
at System.Threading.Tasks.TaskFactory1.FromAsyncCoreLogic(IAsyncResult iar, Func2 endFunction, Action1 endAction, Task1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---

**Comment by kparkov** [comment]
Exactly same issue as @abjrcode here. It doesn't seem like there is any progress or acknowledgement from maintainers?

The issue is also seen randomly when using Github Actions to run tests.

**Comment by xsoheilalizadeh** [comment]
I already have the same issue as [@abjrcode](https://github.com/abjrcode) mentioned above. I'm wondering to know is this abandoned repo, because there isn't any issue response or commits since 4 months ago.

\cc @twright-msft, @LuisBosquez

**Comment by vin-yu** [comment]
Hi All, 

2 things here: 
1.	We are working on a better SQL Server on Windows container story primarily focused on helping folks with dev/test/ci/cd purposes first. No timelines to share other than we are targeting in a few months.
2.	There are challenges with running Linux Containers on Windows when it comes to storage. See https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/linux-containers#bind-mounts.
While we’d love to support all the combinations of different containers and host OS. We currently only support SQL Server on Linux containers for production workloads where the container OS and host OS match. For more information on the support policy for SQL Server containers, see this document.
https://support.microsoft.com/en-us/help/4047326/support-policy-for-microsoft-sql-server

**Comment by marionzr** [comment]
Hi all. I have a similar problem here:

2020-04-19 22:37:11.95 Logon Login failed for user 'sa'. Reason: Failed to open the explicitly specified database 'testing_**e4724b99-fdcb-4ac1-9568-de8106f8b0ac**'. This occurs randomly while peforming my integration tests which create new database.

e4724b99-fdcb-4ac1-9568-de8106f8b0ac is Guid.NewGuid();

I just changed my code as following and the problems have gone.
Note: I'm still doing tests 
from: 
```
var dbName = "testing_" + Guid.NewGuid()
```
to: 
```
var dbName = "testing_" + System.Math.Abs(Guid.NewGuid().GetHashCode());
```

Please let me know if it works for you or if we have another solution.

**Comment by ig-sinicyn** [comment]
@marionzr Thanks a lot for the workaround!

We have same issue and it was resolved after changing the DB name. Wow!

**Comment by ig-sinicyn** [comment]
Well, the issue is still here but it occurs not so often:(
```
System.Data.SqlClient.SqlException : An unexpected error occurred while checking the sector size for file '/var/opt/mssql/data/ba0bjyy_log.ldf'. Move the file to a local NTFS volume, where the sector size can be retrieved. Check the SQL Server error log for more information.
CREATE DATABASE failed. Some file names listed could not be created. Check related errors.
Data:
  HelpLink.ProdName: Microsoft SQL Server
  HelpLink.ProdVer: 14.00.3294
  HelpLink.EvtSrc: MSSQLServer
  HelpLink.EvtID: 5177
  HelpLink.BaseHelpUrl: http://go.microsoft.com/fwlink
  HelpLink.LinkId: 20476
```

**Comment by GeeWee** [comment]
Getting exact same issues running `mcr.microsoft.com/mssql/server:2019-CU4-ubuntu-16.04` on a Fedora 31 workstation, but also on an Ubuntu agent in Azure Pipelines.

C# Stack trace:
```
Error Message:
   Microsoft.Data.SqlClient.SqlException : An unexpected error occurred while checking the sector size for file '/var/opt/mssql/data/oai-testdb-AlarmApiTest_log.ldf'. Move the file to a local NTFS volume, where the sector size can be retrieved. Check the SQL Server error log for more information.
CREATE DATABASE failed. Some file names listed could not be created. Check related errors.
  Stack Trace:
     at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
```

SQL server logs:
```
2020-05-25 14:49:23.34 spid55      Error: 5177, Severity: 16, State: 1.
2020-05-25 14:49:23.34 spid55      An unexpected error occurred while checking the sector size for file '/var/opt/mssql/data/oai-testdb-AlarmApiTest_log.ldf'. Move the file to a local NTFS volume, where the sector size can be retrieved. Check the SQL Server error log for more information.
```

Docker-compose file
```yaml
version: '3.6'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-CU4-ubuntu-16.04"
    container_name: oai-sql-server
    restart: unless-stopped
    volumes:
      - db-data:/var/opt/mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "notMyRealPassword"
    ports:
volumes:
  db-data:
```

This is a major blocker for us in regards to using SQL server in dockerized CI workflows.
