### ISSUE TITLE
Post Installation Failed

### ISSUE THREAD

**Issue by jorgeb12** [Microsoft/mssql-docker#376]
I installed SQL and when try to run the post installation from https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-red-hat?view=sql-server-2017 this errors shows up.

Log:

```
[root@www ~]# sudo /opt/mssql/bin/mssql-conf setup
Error in localization. Using en_US.
Choose an edition of SQL Server:
  1) Evaluation (free, no production use rights, 180-day limit)
  2) Developer (free, no production use rights)
  3) Express (free)
  4) Web (PAID)
  5) Standard (PAID)
  6) Enterprise (PAID)
  7) Enterprise Core (PAID)
  8) I bought a license through a retail sales channel and have a product key to enter.

Details about editions can be found at
https://go.microsoft.com/fwlink/?LinkId=852748

Use of PAID editions of this software requires separate licensing through a
Microsoft Volume Licensing program.
By choosing a PAID edition, you are verifying that you have the appropriate
number of licenses in place to install and run this software.

Enter your edition(1-8): 1
The license terms for this product can be found in
/usr/share/doc/mssql-server or downloaded from:
https://go.microsoft.com/fwlink/?LinkId=855864

The privacy statement can be viewed at:
https://go.microsoft.com/fwlink/?LinkId=853010

Traceback (most recent call last):
  File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 279, in <module>
    main()
  File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 275, in main
    processCommands()
  File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 199, in processCommands
    COMMAND_TABLE[args.which]()
  File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 54, in handleSetup
    exit(mssqlconfhelper.setupSqlServer(eulaAccepted, noprompt=args.noprompt))
  File "/opt/mssql/lib/mssql-conf/mssqlconfhelper.py", line 817, in setupSqlServer
    languageSelect(noprompt)
  File "/opt/mssql/lib/mssql-conf/mssqlconfhelper.py", line 160, in languageSelect
    language = locale.getdefaultlocale()[0]
  File "/usr/lib64/python2.7/locale.py", line 511, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/lib64/python2.7/locale.py", line 443, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
```

**Comment by jorgeb12** [comment]
Hello,
I installed in 
CentOS Linux release 7.5

**Comment by twright-msft** [comment]
ah, ok.  Didnt realize you were using ssh.  Glad you got it sorted out.
