### ISSUE TITLE
Connections closed

### ISSUE THREAD

**Issue by spafcio** [Microsoft/mssql-docker#48]
HI,

I'm having issues running a dockerized mssql-linux in a mac os using boot2docker.
I've restored an image of database.

But under extensive load the following exceptions start to appear:

`NFO   | jvm 1    | main    | 2017/03/14 10:36:40.769 | Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The connection is closed.
INFO   | jvm 1    | main    | 2017/03/14 10:36:40.769 | 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:191)
INFO   | jvm 1    | main    | 2017/03/14 10:36:40.769 | 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.checkClosed(SQLServerConnection.java:710)
INFO   | jvm 1    | main    | 2017/03/14 10:36:40.769 | 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareStatement(SQLServerConnection.java:2953)
INFO   | jvm 1    | main    | 2017/03/14 10:36:40.769 | 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareStatement(SQLServerConnection.java:2592)`

It looks to me that the connections are prematurely closed.

I have tried the following to make deal with the issue:
- upgraded to the newest mssql jdbc driver
- checked the database and server settings regarding the number of worker threads and degree of parallelism

What else an I do to find the root cause? Are there any limitations in the "developer" edition that would result in connections being closed?

**Comment by LuisBosquez** [comment]
There should be no limitations in the preview edition. Can you share how you're running the container vs the app? Also, AFAIK, Docker is recommending Docker Machine over Boot2Docker: [](https://docs.docker.com/machine/migrate-to-machine/)

**Comment by twright-msft** [comment]
Docker for Mac supersedes Docker Machine even. :)
https://docs.docker.com/docker-for-mac/

My first suggestion on troubleshooting this would be to update your environment to Docker for Mac latest version and test again.  That will narrow down the possible causes by eliminating older versions of Docker.

**Comment by spafcio** [comment]
I've moved my containers to Docker for Mac (which I tried some long time ago, and was not an option for me as it had performance problems with host directories mounted as docker volumes).

I currently use 1.7.03 beta which seems to have fixed some of the above mentioned performance problems.

I'm still experiencing the issues with connections being closed - so the issue is not fully solved for me. There isa difference however: after the connections are closed the application reconnects and continues to work.

**Comment by spafcio** [comment]
Additionally I tend to get this kind of exceptions now:

`Mar 20, 2017 2:37:59 PM com.microsoft.sqlserver.jdbc.SQLServerConnection Prelogin
WARNING: ConnectionID:7222 ClientConnectionId: c6186b95-8caa-4650-8ac5-65a451a14ab5 Prelogin error: host localhost port 1433 Error reading prelogin response: Connection reset ClientConnectionId:c6186b95-8caa-4650-8ac5-65a451a14ab5`

**Comment by twright-msft** [comment]
Have you tried testing with a different SQL Server instance, maybe running on a Linux/Windows VM to pinpoint/eliminate the Docker aspect of this as an issue?

**Comment by spafcio** [comment]
I tried with a standard MSSQL server instance installed in a standard VM using windows7. No  problems here. 

I also tried other database types with the application hosting them in docker and no problems there.

I tried with a smaller connection pool in the application and it seemed to help a little but it is not a 'real' solution to the problem.

**Comment by wheelspinner** [comment]
FWIW I am seeing the same issue on docker for mac.  It has only started recently (started sometime in the past week).  Hasn't been a problem in the previous 3 months.  I use the 'latest' and I see it was updated a week ago... coincidence?

I'll dig deeper and try to provide some logs and environment specs.

**Comment by twright-msft** [comment]
Checking with one of our other PMs on this.
@wheelspinner - any update on your investigation?

**Comment by twright-msft** [comment]
@wheelspinner - any updates?

@wheelspinner , @spafcio  - you might want to file this issue over on the JDBC project issues list:
https://github.com/Microsoft/mssql-jdbc/issues

**Comment by wheelspinner** [comment]
Unfortunately no.  I lost the offending image due to a ci push (internal
dtr) and accidental pull with an updated db.  After a couple of hours I
couldn't get it to reproduce like I had before.  I suspect my issue was a
problem with my db that my apps couldn't tolerate.  Both images were the
same base mssql image, just a different version of my db on top.

I didn't have enough time to go back and recreate the original offending
image.

**Comment by twright-msft** [comment]
@wheelspinner darn.
@spafcio  - are you still experiencing some problems?  Do you have a way for us to reproduce what you are seeing?

**Comment by fadsm** [comment]
hello @twright-msft
i've installed sql-server-linux at my macos docker and i'm attempting to connect using DBeaver with JDBC driver. However, i'm receiving the following error:
com.microsft.sqlserver.jdbc.SQLServerException: connection refused.
jdbc url: jdbc:sqlserver://localhost:1433
sql-server-Linux message: Server is listeing on 127.0.0.1<ipv4> 1434
sql-server-Linux message: Server is listeing on 'any'<ipv4> 1433

there is a way to connect sql-server-linux in docker with jdbc over DBeaver at my host machine?

**Comment by gabriellopes** [comment]
Hi @fadsm 

>  jdbc url: jdbc:sqlserver://localhost:1433

try with 1401 port, that is used by docker.

**Comment by imavroukakis** [comment]
I'm actually coming up against this issue, but only when I am running two containers in Docker. If MSSQL is running on its' own, everything is fine. I am using the stock `latest` mssql image and Docker `18.03.0-ce-mac60`
