### ISSUE TITLE
Transaction timeout not causing transaction abort

### ISSUE THREAD

**Issue by KyleAure** [microsoft/mssql-docker#512]
I have the same test that I have run against SQLServer running on bare metal , and the SQLServer docker image (2019-CTP3.1-ubuntu).  
The test passes when run against bare metal, but fails when using the docker image.  

SQL SERVER ON BARE METAL:
```txt
Database product name : Microsoft SQL Server
Database product version : 13.00.1742
JDBC driver name  : Microsoft JDBC Driver 6.0 for SQL Server
JDBC driver version  : 6.0.7728.100
```

SQL SERVER DOCKER
```txt
Database product name : Microsoft SQL Server
Database product version : 15.00.1700
JDBC driver name  : Microsoft JDBC Driver 7.4 for SQL Server
JDBC driver version  : 7.4.1.0
```

TEST CODE
```java
@Test
public void testTransactionTimeout() throws Exception {
    boolean committed = false;
    tran.setTransactionTimeout(8); //set trans timeout to 8 seconds
    tran.begin(); //begin transaction
    long start = System.nanoTime(); //start timer
    try {
        Connection con = ds.getConnection(); //get connection
        try {
            //Execute query then wait 16 seconds
            Statement stmt = con.createStatement(); 
            stmt.executeQuery("SELECT STRVAL FROM MYTABLE WHERE ID=0").close();
            con.createStatement().execute("WAITFOR DELAY '00:00:16'");             //EXPECT SQLException HERE
            long duration = System.nanoTime() - start;
            fail("Statement should have been canceled. Instead it completed after " + TimeUnit.NANOSECONDS.toMillis(duration) + " ms");
        } catch (SQLException x) {
...
    } finally {
...
    }
```

On the bare metal database we see trace that timeout occurred, and the transaction is cancelled (aborted):

```trace
[10/4/19, 10:58:25:267 CDT] 00000050 id=00000000 com.ibm.ws.sqlserver.logwriter                               3 ==> Statement50d9e24b.execute("WAITFOR DELAY '00:00:16'");
[10/4/19, 10:58:32:600 CDT] 00000051 id=00000000 com.ibm.tx.jta.embeddable.impl.EmbeddableTimeoutManager      I WTRN0006W: Transaction 0000016D977E5F53000000015DF97D54CC99C2DAFF788FFEBADBF50378A8F1D8C4438C610000016D977E5F53000000015DF97D54CC99C2DAFF788FFEBADBF50378A8F1D8C4438C6100000001 has timed out after 8 seconds.
[10/4/19, 10:58:32:603 CDT] 00000051 id=00000000 com.ibm.tx.jta.embeddable.impl.EmbeddableTimeoutManager      I WTRN0124I: When the timeout occurred the thread with which the transaction is, or was most recently, associated was Thread[Default Executor-thread-9,5,Default Executor Thread Group]. The stack trace of this thread when the timeout occurred was: 
	java.base/java.net.SocketInputStream.socketRead0(Native Method)
	java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:1877)
	com.microsoft.sqlserver.jdbc.TDSReader.readPacket(IOBuffer.java:6642)
	com.microsoft.sqlserver.jdbc.TDSCommand.startResponse(IOBuffer.java:7959)
	com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:883)
	com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:778)
	com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2444)
	com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:191)
	com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:166)
	com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:751)
...
```
```trace
[10/4/19, 10:58:32:606 CDT] 00000051 id=a04f28ef com.ibm.ws.rsadapter.impl.WSStateManager                     < setState Exit  
                                                                                                               TRANSACTION_ENDING
[10/4/19, 10:58:32:606 CDT] 00000051 id=00000000 com.ibm.ws.sqlserver.logwriter                               3 ==> XAResourcef2d26275.end({XidImpl: formatId(57415344), gtrid_length(36), bqual_length(54),
[10/4/19, 10:58:32:606 CDT] 00000051 id=00000000 com.ibm.ws.sqlserver.logwriter                               3 data(0000016d977e5f53000000015df97d54cc99c2daff788ffebadbf50378a8f1d8c4438c610000016d977e5f53000000015df97d54cc99c2daff788ffebadbf50378a8f1d8c4438c61000000010000000000000000000000000001)}, 536870912);
[10/4/19, 10:58:33:104 CDT] 00000050 id=00000000 com.ibm.ws.sqlserver.logwriter                               3 <== com.microsoft.sqlserver.jdbc.SQLServerException: The Microsoft Distributed Transaction Coordinator (MS DTC) has cancelled the distributed transaction.
[10/4/19, 10:58:33:104 CDT] 00000050 id=00000000 com.ibm.ws.sqlserver.logwriter                               3 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
[10/4/19, 10:58:33:104 CDT] 00000050 id=00000000 com.ibm.ws.sqlserver.logwriter                               3 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1655)
[10/4/19, 10:58:33:104 CDT] 00000050 id=00000000 com.ibm.ws.sqlserver.logwriter                               3 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:885)
[10/4/19, 10:58:33:104 CDT] 00000050 id=00000000 com.ibm.ws.sqlserver.logwriter                               3 	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:778)
[10/4/19, 10:58:33:104 CDT] 00000050 id=00000000 com.ibm.ws.sqlserver.logwriter                               3 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
[10/4/19, 10:58:33:104 CDT] 00000050 id=00000000 com.ibm.ws.sqlserver.logwriter                               3 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2444)
[10/4/19, 10:58:33:104 CDT] 00000050 id=00000000 com.ibm.ws.sqlserver.logwriter                               3 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:191)
[10/4/19, 10:58:33:104 CDT] 00000050 id=00000000 com.ibm.ws.sqlserver.logwriter                               3 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:166)
[10/4/19, 10:58:33:104 CDT] 00000050 id=00000000 com.ibm.ws.sqlserver.logwriter                               3 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:751)
...
```

Whereas, in the docker image we see that the timeout occurs, but the transaction is not aborted and there is no `com.microsoft.sqlserver.jdbc.SQLServerException` thrown:

```trace
[10/4/19, 11:18:19:802 CDT] 0000005a id=00000000 com.ibm.ws.sqlserver.logwriter                               3 ==> Statementa86a3500.execute("WAITFOR DELAY '00:00:16'");
[10/4/19, 11:18:25:376 CDT] 0000005b id=00000000 com.ibm.tx.jta.embeddable.impl.EmbeddableTimeoutManager      I WTRN0006W: Transaction 0000016D9790929C000000015E424A74EABFC27519D27553CDD617036140D7F05D187A580000016D9790929C000000015E424A74EABFC27519D27553CDD617036140D7F05D187A5800000001 has timed out after 8 seconds.
[10/4/19, 11:18:25:380 CDT] 0000005b id=00000000 com.ibm.tx.jta.embeddable.impl.EmbeddableTimeoutManager      I WTRN0124I: When the timeout occurred the thread with which the transaction is, or was most recently, associated was Thread[Default Executor-thread-19,5,Default Executor Thread Group]. The stack trace of this thread when the timeout occurred was: 
	java.base/java.net.SocketInputStream.socketRead0(Native Method)
	java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:2023)
	com.microsoft.sqlserver.jdbc.TDSReader.readPacket(IOBuffer.java:6418)
	com.microsoft.sqlserver.jdbc.TDSCommand.startResponse(IOBuffer.java:7579)
	com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:866)
	com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:768)
	com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194)
	com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2979)
	com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:248)
	com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:223)
	com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:744)
...
```
```trace
[10/4/19, 11:18:25:386 CDT] 0000005b id=00000000 com.ibm.ws.sqlserver.logwriter                               3 ==> XAResourcef9a87e8.end({XidImpl: formatId(57415344), gtrid_length(36), bqual_length(54),
[10/4/19, 11:18:25:387 CDT] 0000005b id=00000000 com.ibm.ws.sqlserver.logwriter                               3 data(0000016d9790929c000000015e424a74eabfc27519d27553cdd617036140d7f05d187a580000016d9790929c000000015e424a74eabfc27519d27553cdd617036140d7f05d187a58000000010000000000000000000000000001)}, 536870912);
[10/4/19, 11:18:35:786 CDT] 0000005a id=00000000 com.ibm.ws.sqlserver.logwriter                               3 <== false
...

[10/4/19, 11:18:35:791 CDT] 0000005a id=00000000 SystemOut                                                    O ERROR: java.lang.AssertionError: Statement should have been canceled. Instead it completed after 18413 ms
[10/4/19, 11:18:35:791 CDT] 0000005a id=00000000 SystemErr                                                    R java.lang.AssertionError: Statement should have been canceled. Instead it completed after 18413 ms
```

It should be noted that in both cases the connection is closed.  
I believe this is an issue since there is no indication to the user of the SQL Server Docker Image why their connection was closed.  Also, in the case of a long running statement, there the transcation is not aborted so we do not have a chance to perform a rollback if necessary.

**Comment by KyleAure** [comment]
It seems this error is still occurring as of mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04.  Any updates on a possible solution?
