### ISSUE TITLE
[Polybase]-[Sample]-[DockerFile]- Update the docker file to have supervisord implementation

### ISSUE THREAD

**Issue by pradm** [microsoft/mssql-docker#557]
https://github.com/microsoft/mssql-docker/blob/master/linux/preview/examples/mssql-polybase/Dockerfile this file doesn't have logic to start both SQL Server and LaunchPadd applications together inside a container. We need to update this to have SupervisorD implementation and have an entrypoint script instead of launching SQL Server. Without this being implemented we cannot test Polybase Feature on SQL Server on Linux Containers as the LaunchPadd is not getting launched with the current docker file generated image file and due to that the DMS is crashing generating a dump.

1/30/2020 10:07:21 PM [Thread:1060] [EngineInstrumentation:TdsCriticalErrorEvent] (Fatal, Low): 
Microsoft.SqlServer.DataWarehouse.Common.ErrorHandling.UnexpectedStatementException: The Remote Java Bridge has not been attached yet. ---> Microsoft.SqlServer.DataWarehouse.Common.ErrorHandling.UnexpectedStatementException: The Remote Java Bridge has not been attached yet. ---> System.Exception: The Remote Java Bridge has not been attached yet.
   at Microsoft.SqlServer.DataWarehouse.DataMovement.Common.ExternalAccess.RemoteBridgeWrapper..ctor(RemoteJavaControlServer remoteJavaControlChannel)
   at Microsoft.SqlServer.DataWarehouse.DataMovement.Common.ExternalAccess.RemoteHadoopBridgeWrapper..ctor(RemoteJavaControlServer remoteJavaControlChannel)
   at Microsoft.SqlServer.DataWarehouse.DataMovement.Common.ExternalAccess.ExternalHadoopBridge.InitializeBridgeWrapper()
   at Microsoft.SqlServer.DataWarehouse.Sql.Statements.AsvFile..ctor(Uri externalUri, FileFormatProperties formatOptions, RejectOptions rejectOptions, IHadoopConfigurationProperties config, Credential credential, ITopologySnapshot topologySnapshot, ExternalFileState fileState, SampleParameters fileSampleParameters, Boolean isCopyCommand, String fedAuthToken)
   at Microsoft.SqlServer.DataWarehouse.Sql.Statements.HadoopFile.GetHadoopFileHandle(Uri absoluteUri, ExternalDataSourceProperties dataSourceOptions, FileFormatProperties formatOptions, RejectOptions rejectOptions, Credential credential, ITopologySnapshot topologySnapshot, ExternalFileState fileState, SampleParameters fileSampleParameters, Boolean isCopyCommand, String fedAuthToken)
   at Microsoft.SqlServer.DataWarehouse.Sql.Statements.HadoopTable.ValidateHadoopFile(ExternalFileState fileState, Boolean createIfNotFound, Boolean validateForExport, Boolean skipExternalValidation)
   at Microsoft.SqlServer.DataWarehouse.Sql.Statements.HadoopTable.ValidateSourceForCreate(Boolean createIfNotFound)
   at Microsoft.SqlServer.DataWarehouse.Sql.Statements.HadoopTable.ObtainTableStatsForHadoopTable(ExternalSourceIdentification externalDataSourceInfo, ExternalFileFormatIdentification externalFileFormatInfo, Int32 rowSizeEstimate, String databaseName, String schemaName, String name, RejectOptions rejectOptions, String fileLocation, IList`1 columns, Boolean createIfNotFound, Boolean specialFilePathColumnOption)
   at Microsoft.SqlServer.DataWarehouse.Sql.Statements.CreateExternalTableStatement.ValidateForSQLServer(ExternalSourceIdentification externalDataSourceInfo, ExternalFileFormatIdentification externalFileFormatInfo)
   at Microsoft.SqlServer.DataWarehouse.Engine.Processors.SqlFrontEndWorkProcessor.OnExecuteRequest()
   at Microsoft.SqlServer.DataWarehouse.Engine.Utils.EventUtils.PublishApplicationEventAndExecute(ApplicationEventTrigger beginTrigger, ApplicationEventTrigger endTrigger, ApplicationEventTrigger errorTrigger, ApplicationEventTrigger cancelTrigger, PublishedEventPayloadDelegate payload, Action callback)
   at Microsoft.SqlServer.DataWarehouse.Engine.Processors.AbstractProcessor.OnProcess()
   at Microsoft.SqlServer.DataWarehouse.Engine.Processors.AbstractProcessor.OnExecute()
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.DataWarehouse.Engine.Processors.AbstractProcessor.OnExecute()
   at Microsoft.SqlServer.DataWarehouse.Engine.Utils.EventUtils.PublishApplicationEventAndExecute(ApplicationEventTrigger beginTrigger, ApplicationEventTrigger endTrigger, ApplicationEventTrigger errorTrigger, ApplicationEventTrigger cancelTrigger, PublishedEventPayloadDelegate payload, Action callback)
   at Microsoft.SqlServer.DataWarehouse.Engine.Processors.AbstractProcessor.Execute()
   at Microsoft.SqlServer.DataWarehouse.Engine.Server.ServerInterface.ProcessorWorker.ExecuteProcessor()
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.DataWarehouse.Engine.Server.ServerInterface.Execute(IQueryContext queryCtx, Boolean isSubBatch, Boolean isBatchInProgress)
   at Microsoft.SqlServer.DataWarehouse.Engine.Server.ServerInterface.OnExecuteRequest(IClientInterface client, String query, Boolean isInBatch, StatementExecutionContext executionContext, IDictionary`2 replacementInfos, String database, Statement pregeneratedStatement, SqlFrontEndRequest request)
   at Microsoft.SqlServer.DataWarehouse.Engine.Server.ServerInterface.ExecuteSqlFrontEndRequest(IClientInterface client, SqlFrontEndRequest request, IEnumerable`1 queryParameters)
   at Microsoft.SqlServer.DataWarehouse.Tds.TdsServiceClient.ProcessRpc(PdwRpcRequest request, String ipcStoredProcName)
   at Microsoft.SqlServer.DataWarehouse.Tds.TdsServiceClient.ExecuteRpc(IntPtr responseWriter, PdwRpcRequest request) [Session.SessionId:SID1007][Session.IsTransactional:False][Query.QueryId:QID1010]
1/30/2020 10:07:26 PM [Thread:1060] [EngineInstrumentation:EngineStopSessionBeginEvent] (Info, Low): Stopping session, in reset connection: False. [Session.SessionId:SID1007][Session.IsTransactional:False]

[root@rhldcom8 /]# docker exec -u root -it sql19 "bash"
root@bfef938949bd:/# ls -l /var/opt/
total 0
drwxrwxrwx 6 root             root              59 Jan 30 19:17 mssql
drwxrwx--x 9 mssql_launchpadd mssql_launchpadd 154 Jan 23 19:37 mssql-extensibility
root@bfef938949bd:/# ls -l /var/opt/mssql-extensibility
total 0
drwxrwx--x 2 mssql_launchpadd mssql_launchpadd 6 Jan 23 19:37 data
drwxrws--x 2 mssql_launchpadd mssql_launchpadd 6 Jan 23 19:37 externallanguages
drwxrws--x 2 mssql_launchpadd mssql_launchpadd 6 Jan 23 19:37 externallanguagestemp
drwxrws--x 2 mssql_launchpadd mssql_launchpadd 6 Jan 23 19:37 externallibraries
drwxrws--x 2 mssql_launchpadd mssql_launchpadd 6 Jan 23 19:37 externallibrariestemp
drwxrwx--x 2 mssql_launchpadd mssql_launchpadd 6 Jan 23 19:37 log
drwxrwx--x 2 mssql_launchpadd mssql_launchpadd 6 Jan 23 19:37 sandboxes
 
Some times only externallibraries and externallibrariestemp folders only exist and the others are missing
 
root@bfef938949bd:/# ls -l /var/opt/mssql-extensibility/log
total 0
root@bfef938949bd:/# ls -l /var/opt/mssql-extensibility/externallibraries
total 0
 
root@bfef938949bd:/# ls -l /opt/
total 0
drwxr-xr-x 4 root root 28 Jan 23 19:36 mssql
drwxr-xr-x 4 root root 28 Jan 23 19:37 mssql-extensibility
root@bfef938949bd:/# ls -l /opt/mssql-extensibility
total 0
drwxr-xr-x 2 root root  38 Jan 23 19:37 bin
drwxr-xr-x 2 root root 166 Jan 23 19:37 lib
root@bfef938949bd:/# ls -l /opt/mssql-extensibility/bin
total 5888
-rwxr-xr-x 1 root root 1059800 Dec 19 21:56 exthost
-rwxr-xr-x 1 root root 4966536 Dec 19 21:56 launchpad
 
root@bfef938949bd:/# ls -l /opt/mssql-extensibility/lib
total 3516
-rw-r--r-- 1 root root  355168 Dec 19 21:56 commonlauncher.so
-rw-r--r-- 1 root root  192943 Dec 19 21:56 java-lang-extension.tar.gz
-rw-r--r-- 1 root root  950376 Dec 19 21:56 libc++.so.1
-rw-r--r-- 1 root root  307496 Dec 19 21:56 libc++abi.so.1
-rw-r--r-- 1 root root   11235 Dec 19 21:56 mssql-java-lang-extension.jar
-rw-r--r-- 1 root root 1768320 Dec 19 21:56 sqlsatellite.so
 
root@bfef938949bd:/# ls -l /opt/mssql/lib/hadoop/Content/
total 134176
drwxr-xr-x 2 root root     4096 Jan 23 19:37 CHD
drwxr-xr-x 2 root root     4096 Jan 23 19:37 CHD5
drwxr-xr-x 2 root root      244 Jan 23 19:37 HDP
drwxr-xr-x 2 root root     4096 Jan 23 19:37 HDP2
drwxr-xr-x 2 root root     4096 Jan 23 19:37 HDP2_2
-rw-r--r-- 1 root root    35020 Dec 19 21:58 HdfsBridge.jar
drwxr-xr-x 2 root root     4096 Jan 23 19:37 Windows
drwxr-xr-x 2 root root     4096 Jan 23 19:37 Windows2
-rw-r--r-- 1 root root 25853702 Dec 19 22:01 cloudera5_polybase.jar
-rw-r--r-- 1 root root 25850586 Dec 19 22:05 cloudera_polybase.jar
-rw-r--r-- 1 root root 28332716 Dec 19 22:03 hortonworks2_2_polybase.jar
-rw-r--r-- 1 root root 28324898 Dec 19 22:00 hortonworks2_polybase.jar
-rw-r--r-- 1 root root 28960222 Dec 19 22:07 polybase.jar
 
            root@bfef938949bd:/# ls -l /var/opt/mssql/log/polybase/dump
total 1154388
-rw-r----- 1 root root     24868 Jan 30 22:07 SQLDUMPER_ERRORLOG.log
-rw-r----- 1 root root 587170486 Jan 30 21:26 SQLDmpr.00000000914E239B.GMT-2020-01-30-21-00-00.dmp
-rw-r----- 1 root root 594887806 Jan 30 22:07 SQLDmpr.00000000EE14F8F9.GMT-2020-01-30-22-00-00.dmp

**Comment by Sergepetroff** [comment]
also tried to add Polybase and stuck on:
```
sudo apt-get remove mssql-server-polybase
sudo apt-get update 
sudo apt-get install mssql-server-polybase
mssql:/$ sudo
bash: sudo: command not found
```

**Comment by sandermvanvliet** [comment]
@Sergepetroff I ran into the same issue and changed the dockerfile to:
```
FROM mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04

# Change context to root user (default is mssql)
USER root

RUN apt-get remove mssql-server-polybase
RUN apt-get update
RUN apt-get install mssql-server-polybase

# Change context back to mssql user
USER mssql

# Run SQL Server process
CMD ["/opt/mssql/bin/sqlservr"]
```

**Comment by kentmaxwell** [comment]
I am experiencing the same problem.  It is not possible to use the HADOOP connector with Polybase in an MSSQL container.  I get the same error 'The Remote Java Bridge has not been attached yet.' when I attempt to create an external table to a HADOOP source.  I understand the issue is because the launchpadd service is not running.  However, this service will not run in the container.  When it is invoked it returns the following error:

launchpadd: Operation not permitted

It is my understanding that being able to run Polybase with the HADOOP connector in a container is suppose to be possible.  I am running SQL Server CU9.  I doubt this is working for anyone.
