### ISSUE TITLE
Unable to connect to SQL Server from python docker image: pyodbc.OperationalError: ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x2746 (10054) (SQLDriverConnect)')

### ISSUE THREAD

**Issue by visimo-jarod** [microsoft/mssql-docker#636]
My company built a web application using Flask that houses Dash apps for our clients within a central hub and we are trying to now deploy this application to a Kubernetes cluster. In trying to containerize the application and its dependent services, I'm encountering the error below.

```
/usr/local/lib/python3.8/site-packages/pandas_datareader/compat/__init__.py:7: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 425, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/code/runprod.py", line 12, in <module>
    server = create_app()
  File "/code/app/__init__.py", line 102, in create_app
    register_dashapp(
  File "/code/app/__init__.py", line 239, in register_dashapp
    my_dashapp.layout = layout
  File "/usr/local/lib/python3.8/site-packages/dash/dash.py", line 474, in layout
    layout_value = self._layout_value()
  File "/usr/local/lib/python3.8/site-packages/dash/dash.py", line 440, in _layout_value
    return self._layout() if self._layout_is_function else self._layout
  File "/code/app/clima_compensation_analytics/layout.py", line 25, in get_layout
    df = run_etl()
  File "/code/app/clima_compensation_analytics/etl.py", line 14, in run_etl
    clima_db = pyodbc.connect(
pyodbc.OperationalError: ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x2746 (10054) (SQLDriverConnect)')
```

I believe that I have installed all of the necessary drivers and my Dockerfile looks like this:

```docker
FROM python:3
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update
RUN ACCEPT_EULA=Y apt-get install -y --allow-unauthenticated msodbcsql17
RUN ACCEPT_EULA=Y apt-get install -y --allow-unauthenticated mssql-tools
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
RUN apt-get install unixodbc-dev
RUN apt-get install libgssapi-krb5-2
RUN pip install -r requirements.txt
COPY . /code/
```

The code that is crashing looks like this (with the password and username obviously not redacted):

```
db = pyodbc.connect(
	'Driver={ODBC Driver 17 for SQL Server};'
	'Server=***.***.***.***;'
	'Database=******;'
	'UID=******'
	'PWD=******'
)
```

As far as I can tell, it seems like the issue is with the connection of the ODBC driver to the server from a docker container. I get the above error whether I attempt to execute the container on the cluster or on my local machine. I managed to exec into one of the service pods on the cluster that the web server is dependent on and ping'd the server IP so I believe that this isn't an issue with my network or the cluster's network or something like that.

**Comment by trutane** [comment]
I get the same error calling `pyodbc.connect()` when using **python 3** with ODBC Driver 17, which I do not see when using **python 2** with the same driver, and using python code that is not python 2 or 3 specific.

The exact same TCP Provider error can also arise from SSL version issues: https://github.com/mkleehammer/pyodbc/issues/610

but I don't think the SSL version is the culprit here since things are working fine with python2 + Driver 17, on the same system (CentOS 8.2). Note that using python3 with Driver 11 on CentOS 6 was not a problem (the old system we're migrating from).

My python3 and pyodbc library were installed with python3-based conda, btw: 
`conda3/1.0.1/env/lib/python3.7/site-packages/pyodbc.cpython-37m-x86_64-linux-gnu.so`

So in my case, the trouble could be coming from the conda3 environment.

**Comment by ashkspark** [comment]
I am facing the same problem with pypyodbc. Any updates?

**Comment by visimo-jarod** [comment]
I never got this to work for my application, I ended up switching to use pymssql. This obviously won't work for all projects, only those using MSSql.

**Comment by bck01215** [comment]
It seems to be [openssl incompatibility with your server version](https://support.microsoft.com/en-us/topic/kb4548001-fix-connection-error-occurs-when-you-try-to-connect-sql-server-2017-on-linux-by-using-openssl-1-1-a2eca71a-a412-3281-dbf8-fe933dba26e7).
The server I tried conenction to was  Microsoft SQL Server 2008 R2
 
I was able to get this to work by changing my openssl version to 1.1.1l (was 1.1.1k)

here's the RUN statement to do that:

```
RUN wget https://www.openssl.org/source/openssl-1.1.1l.tar.gz -O openssl-1.1.1l.tar.gz && \
    tar -zxvf openssl-1.1.1l.tar.gz && cd openssl-1.1.1l && ./config && make&& \
    make install && ldconfig
```
