### ISSUE TITLE
Enable full-text search in mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04

### ISSUE THREAD

**Issue by deepesh-verma** [microsoft/mssql-docker#665]
We are using the below container tag - 
mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04

While trying to create full-text catalog, we are getting below error - 
**Query** - CREATE FULLTEXT CATALOG testCatalog AS DEFAULT;
```
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Cannot use full-text search in master, tempdb, or model database.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1624)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:868)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:768)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194)

```

Can you please help me with installing/enabling full-text search?

**Comment by yardenshoham** [comment]
I'm having the same issue. Were you able to solve it?
