### ISSUE TITLE
Mac M1 running MS SQL on Docker, unable to connect from SQL client tools

### ISSUE THREAD

**Issue by dantoniazi** [microsoft/mssql-docker#795]
Hi,
I'm facing some problems on my M1 Macbook when I try to connect to a MS SQL instance on Docker from Azure Data Studio or Dbeaver.

Steps to Reproduce:
Download and install Docker Desktop for ARM (https://desktop.docker.com/mac/main/arm64/Docker.dmg)
Download Azure SQL Edge image (run the command: docker pull mcr.microsoft.com/azure-sql-edge)
Launch an instance of the image (run the command: docker run -e 'ACCEPT_EULA=1' -e 'MSSQL_SA_PASSWORD=Password123' -p 1433:1433 --name sqlserver -d mcr.microsoft.com/azure-sql-edge)
Once created and running properly, download Azure Data Studio for ARM (from https://go.microsoft.com/fwlink/?linkid=2215346)
Azure Data Studio -> New Connection -> Connection type: Microsoft SQL Server; Server: localhost; user: sa; password: Password123; Trust Server Certificate=True or False (it makes no difference)

This is the verbose log I got from Azure Data Studio:
Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 0 - 30164676)
---> System.ComponentModel.Win32Exception (301646768): Unknown error: 301646768
at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
at Microsoft.Data.SqlClient.TdsParserStateObject.ThrowExceptionAndWarning(Boolean callerHasConnectionLock, Boolean asyncClose)
at Microsoft.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
at Microsoft.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
at Microsoft.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
at Microsoft.Data.SqlClient.TdsParser.ConsumePreLoginHandshake(SqlConnectionEncryptOption encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean& marsCapable, Boolean& fedAuthRequired, Boolean tlsFirst)
at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, SqlConnectionString connectionOptions, Boolean withFailover)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
at Microsoft.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
at Microsoft.Data.ProviderBase.DbConnectionFactory.<>c_DisplayClass48_0.b0(Task1 ) at System.Threading.Tasks.ContinuationResultTaskFromResultTask2.InnerInvoke()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c_DisplayClass30_0.<b_0>d.MoveNext() in D:\a_work\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 316
--- End of stack trace from previous location ---
at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 709
ClientConnectionId:4d442c18-293e-4f3e-89ca-1fe78fc5b897
Error Number:301646768,State:0,Class:20

I also try to connect from another tool (Dbeaver), and I got a similar error:
"The TCP/IP connection to the host localhost, port 1433 has failed. Error: "The driver received an unexpected pre-login response. Verify the connection properties and check that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. This driver can be used only with SQL Server 2005 or later.". ClientConnectionId:7e7c151e-2eeb-47fa-8a2b-27ddec374c03"

Besides, I also tried exactly the same steps on a Macbook Intel and everything went well (in both Azure and Dbeaver). I got those errors just on Macbook M1.

Docker version: 20.10.21, build baeda1f
OS Version: MacOS 13.0.1 (Macbook Pro 2020, Chip Apple M1, Memory 8 GB)

At first, I thought the problem was with Azure Data Studio, then I created an issue there:
https://github.com/microsoft/azuredatastudio/issues/21367
After some attempts, they suggested me to open an issue here.

Do you have any suggestion?

**Comment by dzsquared** [comment]
@dantoniazi  - can you share the output of the container logs and inspect info?
```bash
docker logs sqlserver
docker inspect sqlserver
```

**Comment by ys64** [comment]
I encountered not an exact issue, but a similar issue. I needed to connect from another container to mssql container, and it turned out that I had to specify the IP address of mssql container, instead of `localhost`.

```
docker container ls
docker inspect (container_id) | grep IPAddress
```

I used the IP address, and was able to connect to the mssql container from the other container. It might be worth of trying if you are still stuck with this issue.
