### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by jez9999** [microsoft/mssql-docker#812]
I've setup a Docker container on Debian 10.3 with mcr.microsoft.com/mssql/server:2022-latest.  I run it like this:

> sudo docker run --name "sqlsvr2022" -p 1433:1433 -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=T3st1ngP@ssW0rd!" -e "MSSQL_PID=Developer" mcr.microsoft.com/mssql/server:2022-latest

I then have a test C# program I run to try and connect to it on the same box by connecting to `localhost,1433` in the connection string:

> Master ConnectionString => Data Source=localhost,1433;Initial Catalog=master;Integrated Security=False;User ID=sa;Password=******;Connect Timeout=30;Trust Server Certificate=True;Application Intent=ReadWrite;Multi Subnet Failover=False

It appears that for some reason, the server is just abruptly terminating the connection and there's no useful error given.  Here's the exception chain my application throws:

```
=====================================================
::
:: Exception (Microsoft.Data.SqlClient.SqlException):
::
* Errors: Microsoft.Data.SqlClient.SqlErrorCollection
* ClientConnectionId: 3893862b-193d-4d2d-aa82-d9530af81470
* Class: 20
* LineNumber: 0
* Number: 0
* Procedure:
* Server: localhost,1433
* State: 0
* Source: Core Microsoft SqlClient Data Provider
* IsTransient: False
* SqlState: [null]
* BatchCommand: [null]
* ErrorCode: -2146232060
* TargetSite: Void OnError(Microsoft.Data.SqlClient.SqlException, Boolean, System.Action`1[System.Action])
* Message: A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)
* Data: System.Collections.ListDictionaryInternal
* HelpLink: [null]
* HResult: -2146232060
* StackTrace:    at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParserStateObject.ThrowExceptionAndWarning(Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   at Microsoft.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   at Microsoft.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   at Microsoft.Data.SqlClient.TdsParser.ConsumePreLoginHandshake(SqlConnectionEncryptOption encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean& marsCapable, Boolean& fedAuthRequired, Boolean tlsFirst)
   at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, SqlConnectionString connectionOptions, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at SqlServerExtensions.SqlDatabase(SupportedDatabasesForEnsureDatabase supported, String connectionString, IUpgradeLog logger, Int32 timeout, AzureDatabaseEdition azureDatabaseEdition, String collation) in /_/src/dbup-sqlserver/SqlServerExtensions.cs:line 252
   at Mystikaze.DBMigrator.DBMigrator.Run() in C:\Development\Mystikaze\Mystikaze.DBMigrator\DBMigrator.cs:line 105


:: ::
:: :: InnerException (System.IO.IOException):
:: ::
* TargetSite: Int32 Read(Byte[], Int32, Int32)
* Message: Unable to read data from the transport connection: Connection reset by peer.
* Data: System.Collections.ListDictionaryInternal
* HelpLink: [null]
* Source: System.Net.Sockets
* HResult: -2146232800
* StackTrace:    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.Data.SqlClient.SNI.SNIPacket.ReadFromStream(Stream stream)
   at Microsoft.Data.SqlClient.SNI.SNITCPHandle.Receive(SNIPacket& packet, Int32 timeoutInMilliseconds)


:: :: ::
:: :: :: InnerException (System.Net.Sockets.SocketException):
:: :: ::
* Message: Connection reset by peer
* SocketErrorCode: ConnectionReset
* ErrorCode: 104
* NativeErrorCode: 104
* TargetSite: Int32 Read(Byte[], Int32, Int32)
* Data: System.Collections.ListDictionaryInternal
* InnerException: [null]
* HelpLink: [null]
* Source: System.Net.Sockets
* HResult: -2147467259
* StackTrace:    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count)
=====================================================
```

I've also tried connecting to the terminal with PuTTY, port forwarding 1433, and connecting with SSMS to my localhost port 1433.  I get a similar error there:

> A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 0 - An existing connection was forcibly closed by the remote host.) (Framework Microsoft SqlClient Data Provider)

So this definitely seem to be some kind of problem with accessing SQL Server through the Docker container.  I've also tried with the SQL Server 2019 latest image, with exactly the same error.

**Comment by jez9999** [comment]
Turns out it was my local firewall configuration that needed to have outgoing TCP 1433 connections opened up.  I had assumed that as I was connecting to localhost this wasn't needed but it seems Docker connections count as outgoing TCP connections.
